import $ from "./core";
import "./modules/handlers";
import "./modules/display";
import "./modules/classes";
import "./modules/attributes";
import "./modules/actions";
import "./modules/width";
import "./modules/height";
import "./modules/transform";
import "./components/calcScroll";
import "./components/dropdown";
import "./components/modal";
import "./components/tab";
import "./components/accordion";
import "./components/carousel";
import "./services/request";
import "./animation/effects";
import "./animation/fadeIn";
import "./animation/fadeOut";
import "./animation/fadeToggle";

export default $;
